<?php

/**
 * AlbumTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlbumTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object AlbumTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('Album');
  }
  
  /**
   * Add an Album to the database or get its key if it exists
   * @param name str: the name of the album to add
   * @return     int: the primary key added or found
   */
  public function addAlbum( $name )
  {
    //is this name already in the collection?
    $q = Doctrine_Query::create()
      ->select( 'a.id' )
      ->from( 'Album a' )
      ->where( 'a.name = ?', $name);
    $result = $q->fetchOne();
     
    if ( is_object( $result ) && $result->id > 0 )
    {
      return $result->id;
    }
    else
    {
      $item = new Album;
      $item->name = $name;
      $item->save();
      return $item->getId();
    }
  }
  
  /**
   * Fetch the album list
   * @param alpha str: the alphabetical grouping
   * @return      array: of all album entries
   */
  public function getList( $alpha = 'all', $artist_id = 'all')
  {
    $q = Doctrine_Query::create()
      ->select( 'a.id, a.name' )
      ->from( 'Album a, Song s' )
      ->where( 'a.id = s.album_id' );
    if( $alpha !== 'all' )
    {
      $q->andWhere( 'a.name LIKE ?', substr( $alpha, 0, 1 ) . '%' );
    }
    if( $artist_id !== 'all' )
    {
      $q->andWhere( 's.artist_id = ?', $artist_id );
    }
    $q->distinct();
    $q->orderBy( 'a.name ASC' );
    return $q->fetchArray();
  }
  
  /**
   * Update an album to flag it as scanned for a give source
   * @param album_id int: the album id field to update
   * @param scan_id  int: the scan id 
   * @param source   str: the artwork source: amazon|meta|folders|service etc.
   * @return         bool: true if record updated, otherwise false
   */
  public function setSourceScanned( $album_id, $scan_id, $source )
  {  
    $query  = 'UPDATE ';
    $query .= ' album ';
    $query .= 'SET ';
    switch ( $source )
    {
      case 'amazon':
        $query .= ' amazon_flagged = 1, ';
        break;
      
      case 'meta':
        $query .= ' meta_flagged = 1, ';
        break;
        
      case 'folders':
        $query .= ' folders_flagged = 1, ';
        break;
      
      case 'service':
        $query .= ' service_flagged = 1, ';
        break;
    }
    $query .= ' album.scan_id = :scan_id ';
    $query .= 'WHERE ';
    $query .= ' album.id = :album_id ';
    
    $params = array( 
                    'scan_id' => $scan_id,
                    'album_id' => $album_id,
                   );
    
    $dbh = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh(); 
    $stmt = $dbh->prepare( $query );
    $result = $stmt->execute( $params );
    if ( $stmt->rowCount() > 0 )
    {
      return true;
    }
    return false;
  }
}