<?php

/**
 * AlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlbumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Album');
    }
    
    /**
    * Fetch the album list
    * @param alpha str: the alphabetical grouping 
    * @return      array: of all album entries
    */
    public function getList( $alpha = 'all', $artist_id = 'all')
    {
      $q = Doctrine_Query::create()
        ->select( 'a.id, a.name' )
        ->from( 'Album a, Song s' )
        ->where( 'a.id = s.artist_id' );
      if( $alpha !== 'all' )
      {
        $q->andWhere( 'a.name LIKE ?', substr( $alpha, 0, 1 ) . '%' );
      }
      if( $artist_id !== 'all' )
      {
        $q->andWhere( 's.artist_id = ?', $artist_id );
      }
      $q->distinct();
      $q->orderBy( 'a.name ASC' );
      return $q->fetchArray();
    }
}