<?php

/**
 * EchonestPropertiesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EchonestPropertiesTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object EchonestPropertiesTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('EchonestProperties');
  }
  
  /**
   * Add echonest song information to the local database
   *
   * @param song_id int: streeme song primary key
   * @param details arr: key value pairs for echonest song details
   */
  public function addSongData($song_id, $details = array())
  {
    if(is_array($details) && count($details) > 0)
    {
      foreach($details as $key=>$value)
      {
        
      }
    }
  }
}