<?php
/*
* combines javascript and css assets
*
* @package    streeme
* @subpackage combineFiles
* @author     Richard Hoar
*/
class combineFiles
{
  /**
   * Combine multiple text assets into a single file for better http performance
   *
   * @param type      string css or js
   * @param namespace string the combined file namespace (eg. module+action names)
   * @param response  object the sfWebResponse instance
   * @return          string the path and filename generated by the combiner
   */
  public function combine( $type, $namespace, sfWebResponse $response )
  {
    //configure the combiner
    $fullname = ( $type === 'css' ) ? 'Stylesheets' : 'Javacripts';
    $response_getter = 'get' . $fullname;
    $namespace = StreemeUtil::slugify( $namespace );
    
    //integrate into symfony's asset globals
    sfConfig::set( sprintf( 'symfony.asset.%s_included', strtolower( $fullname ) ), true);
  
    //build the cache filename - this file will be regenerated on a symfony cc
    $path     = sprintf('%s/combine/%s/',
                         sfConfig::get('sf_cache_dir'),
                         $type
                        );
    $filename = sprintf( '%s.%s',
                         $namespace,
                         $type
                        ); 
    if( !is_readable( $path . $filename ) )
    {
      //build one file of all of the css or js files
      $file_content = '';
      foreach ($response->$response_getter() as $file => $options)
      {
        $file_content .= file_get_contents( sfConfig::get('sf_web_dir') . $file ) . "\r\n";
      }
      @mkdir( $path, 0777, true );
      file_put_contents( $path . $filename , $file_content );
    }
    
    return sprintf( '/service/combine/%s/%s/combine.%s', $type, $namespace, $type );
  }
  
  /**
   * Get a combined file from the cache lib
   * 
   * @param type      string css or js
   * @param namespace string the combined file namespace (eg. module+action names)
   */
  public function getFileName( $type, $namespace )
  {
    $type = ( $type === 'css' ) ? 'css' : 'js';
    $namespace = StreemeUtil::slugify( $namespace );
    
    return sprintf('%s/combine/%s/%s.%s',
                     sfConfig::get('sf_cache_dir'),
                     $type,
                     $namespace,
                     $type
                    );                     
  }
}