<?php
/*
* combines javascript and css assets
*
* @package    streeme
* @subpackage combineFiles
* @author     Richard Hoar
*/
class combineFiles
{
  /**
   * Generate a combines file of multiple css files
   *
   * @param namespace string the combined file namespace (eg. module+action names)
   * @return          string the path and filename generated by the combiner
   */
  public function combineStylesheets( $namespace )
  {
    $response = sfContext::getInstance()->getResponse();
    sfConfig::set('symfony.asset.stylesheets_included', true);
  
    $file_content = '';
    foreach ($response->getStylesheets() as $file => $options)
    {
      $file_content .= file_get_contents( sfConfig::get('sf_web_dir') . $file) . "\r\n";
    }
    $filename = sfConfig::get('sf_web_dir') . '/css/' . StreemeUtil::slugify( $namespace ) . 'combined.css';
    file_put_contents( $filename , $file_content );
    return str_replace(  sfConfig::get('sf_web_dir'), '', $filename );
  }
  
  /**
   * Generate a combines file of multiple css files
   *
   * @param namespace string the combined file namespace (eg. module+action names)
   * @return          string the path and filename generated by the combiner
   */
  public function combineJavascripts( $namespace )
  {
    $response = sfContext::getInstance()->getResponse();
    sfConfig::set('symfony.asset.javascripts_included', true);
  
    $file_content = '';
    foreach ($response->getJavascripts() as $file => $options)
    {
      $file_content .= file_get_contents( sfConfig::get('sf_web_dir') . $file) . "\r\n";
    }
    $filename = sfConfig::get('sf_web_dir') . '/js/' . StreemeUtil::slugify( $namespace ) . 'combined.js';
    file_put_contents( $filename , $file_content );
    return str_replace(  sfConfig::get('sf_web_dir'), '', $filename );
  }
}