<?php

/**
 * ScanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Scan');
    }
}