<?php

/**
 * ArtistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArtistTable extends Doctrine_Table
{
  /**
     * Returns an instance of this class.
     *
     * @return object ArtistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Artist');
    }
    
    /**
    * Fetch the artist list
    * @param alpha str: the alphabetical grouping 
    * @return      array: of all artist entries
    */
    public function getList( $alpha = 'all' )
    {
      //get the song from the database
      $q = Doctrine_Query::create()
        ->select( 'a.id, a.name' )
        ->from( 'Artist a' );
      if( $alpha !== 'all' )
      {
        $q->where( 'a.name LIKE ?', substr( $alpha, 0, 1 ) . '%' );
      }
      $q->orderBy( 'a.name ASC' );
      return $q->fetchArray();
    }
}