<?php

/**
 * PlaylistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlaylistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlaylistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Playlist');
    }
    
    /**
    * Fetch the playlist list
    * @param alpha str: the alphabetical grouping 
    * @return      array: of all genre entries
    */
    public function getList( $alpha = 'all' )
    {
      $q = Doctrine_Query::create()
        ->select( 'p.id, p.name' )
        ->from( 'Playlist p' );
      if( $alpha !== 'all' )
      {
        $q->where( 'p.name LIKE ?', substr( $alpha, 0, 1 ) . '%' );
      }
      $q->orderBy( 'p.name ASC' );
      return $q->fetchArray();
    }
}