<?php

/**
 * PlaylistFilesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlaylistFilesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlaylistFilesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlaylistFiles');
    }
}